# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('link', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('vote', models.CharField(choices=[('UP', 'LIKE'), ('DOWN', 'UNLIKE')], max_length=20)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstories.Stories')),
            ],
        ),
    ]
