# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstories.Stories')),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='story',
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
